UI and UX improvements
calinvladth/map-organiser pull request #1
Opened 2024-08-26 21:06 UTC by baptistebisson

I've made multiple commits so it's easier to review.

Mostly UI and UX to try to improve the design. Not sure if you're willing to have rounded borders.

2024-08-26 22:18 UTC, calinvladth requested changes

2024-08-26 22:18 UTC, calinvladth commented on src/routes/app/maps/create/+page.svelte
> +    alertSuccess.set('Map `'+ form.name +'` created.');
You can use `successHandler` from `utils/alertHandler`. There is some logic that clears the alert from the view.
By using `alertSuccess` directly, it works, but it's a bypass.

2024-08-26 22:18 UTC, calinvladth commented on src/routes/app/+page.svelte
> +      <p><a href="{ROUTES.MAPS_CREATE}" class="underline">Create your first map</a></p>
paragraph can be removed, just leave the anchor

2024-08-26 22:18 UTC, calinvladth commented on src/routes/app/+page.svelte
> +  <h1 class="text-3xl p-5 border-b border-black">Maps{@html maps.length > 0 ? " <small>(" + maps.length + ")</small>": ""}</h1>
Nitpicking, I think it's easier to read like this: 
`Maps {@html maps.length > 0 ? "<small>(" + maps.length + ")</small>": ""}`

2024-08-27 07:24 UTC, baptistebisson commented on src/routes/app/+page.svelte
> +  <h1 class="text-3xl p-5 border-b border-black">Maps{@html maps.length > 0 ? " <small>(" + maps.length + ")</small>": ""}</h1>
You only added space outside ?

2024-08-27 07:24 UTC, baptistebisson commented on src/routes/app/maps/create/+page.svelte
> +    alertSuccess.set('Map `'+ form.name +'` created.');
Didn't see it, thanks

2024-08-27 07:26 UTC, baptistebisson commented
I've pushed the modification. 

Had some issues on linux, pocketbase doesn't work, I had to download it.
Shouldn't we remove it from repo ? Pretty heavy (but too late now) and use a bash script to setup the project.

We should also use .env file to specify the connection port (default port is already taken for me)

2024-08-27 08:01 UTC, calinvladth commented on src/routes/app/+page.svelte
> +  <h1 class="text-3xl p-5 border-b border-black">Maps{@html maps.length > 0 ? " <small>(" + maps.length + ")</small>": ""}</h1>
Yes

2024-08-27 08:09 UTC, calinvladth commented
> I've pushed the modification.
> 
> Had some issues on linux, pocketbase doesn't work, I had to download it. Shouldn't we remove it from repo ? Pretty heavy (but too late now) and use a bash script to setup the project.
> 
> We should also use .env file to specify the connection port (default port is already taken for me)

This is a good idea, thank you for suggesting.

2024-08-27 08:11 UTC, merged